version: 0.1

phases:
  pre_build:
    commands:
      - aws configure --aws_access_key_id "${AWS_Access_Key_ID}" --aws_secret_access_key "${AWS_Secret_Access}" --Default_region_name $"{region_name}"
      - echo `date +%s`
      - echo Logging into Amazon ECR...
      - aws ecr get-login --region us-east-2
      - docker login --username AWS --password-stdin 435682496595.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building and tagging container
      - docker build -t test .
      - docker tag test:latest 435682496595.dkr.ecr.us-east-2.amazonaws.com/test:latest
  post_build:
    commands:
      - echo Pushing docker image
      - docker push 435682496595.dkr.ecr.us-east-2.amazonaws.com/test:latest
